language: java

dist: trusty
sudo: required

jdk:
  - openjdk7
  - oraclejdk8

before_script: openssl s_client -CApath /etc/ssl/certs/ -connect plugins.gradle.org:443 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/gradle.crt; sudo keytool -importcert -noprompt -file /tmp/gradle.crt -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts -alias root -storepass changeit

script: for mod in cadc-vosi cadc-registry cadc-registry-server cadc-test-vosi; do cd $mod; gradle assemble check javadoc install || break -1; cd ..; done

