<<<<<<< HEAD
name: Java CI

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: build and test cadc-registry
      run: cd cadc-registry && gradle --info clean build javadoc checkstyleMain install
      
      
    - name: build and test cadc-vosi
      run: cd cadc-vosi && gradle --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-inventory-db
      run: cd cadc-inventory-db && gradle --info clean build javadoc checkstyleMain  install
      
    - name: build and test cadc-registry-server
      run: cd cadc-registry-server && gradle --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-test-vosi
      run: cd cadc-test-vosi && gradle --info clean build javadoc checkstyleMain install
